name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-tools-git

    - name: Initialize and update submodule
      run: |
        git submodule update --init --recursive
    
    - name: Run build script
      run: .\build.bat

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}
        release_name: Release ${{ github.event.release.tag_name }}
        body: |
          Release ${{ github.event.release.tag_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
