name: Build and Release

on:
  push:
    branches:
      - linux

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential 

    - name: Initialize and update submodule
      run: |
        git submodule update --init --recursive
    
    - name: Run build script
      run: ./build.sh

    - run:   |
         upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
         echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
      shell: bash
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ env.UPLOAD_URL }}
        asset_path: ./out/tlf
        asset_name: linux-tlf
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}