name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: gcc mingw-w64-x86_64-gcc mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-tools-git

    - name: Initialize and update submodule
      run: |
        git submodule update --init --recursive
    
    - name: Run build script
      run: .\build.bat

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        body: |
            "Newest releast"
        draft: false
        prerelease: false